---
# TODO: Maybe put a changed_when because it always shows changed.

- hosts: development
  vars:
      host: "{{ inventory_hostname }}"
      project_ssh_port: 50777
  roles:
    - deploy-xserver-for-development-machine
    - provision-projects-ssh-keys
    - deploy-functional-test-tools
    - role: provision-django-project
      project_port: 50778
      project_name: tdd_django_ottg
    - role: deploy-django-project
      project_name: tdd_django_ottg
      repository: git@github.com:civilian/tdd_django_ottg.git
    - role: deploy-django-project-to-run-tests
      project_name: tdd_django_ottg

    # Installing blog_django
    - role: provision-django-project
      project_port: 50779
      project_name: blog_django
    - role: deploy-django-project
      project_name: blog_django
      repository: git@github.com:civilian/blog_django.git
    - role: deploy-django-project-to-run-tests
      project_name: blog_django
